export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_INDIVIDUAL_PRODUCTS = 'FETCH_INDIVIDUAL_PRODUCTS';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_TOYS_FAILURE';
export const FETCH_REMAINING_PRODUCT = 'FETCH_REMAINING_PRODUCT'
export const LOADING = 'LOADING';